### ISSUE TITLE
Support relaying for Sovereign SDK chains

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes-sdk#10]
## Background

As part of Sovereign's efforts to integrate IBC into the Sovereign SDK, they will require an IBC relayer that is capable of signing and sending Sovereign transactions. 

Currently, the plan is to implement the necessary functionality in the relayer-next framework in order to support Sovereign relaying. As such, this work will serve as relayer-next's first concrete use-case. 

### Tasks
- [X] Integration of `sov-ibc` modules with sovereign rollup starter https://github.com/informalsystems/sovereign-ibc/issues/67
- [x] Basic integration test for Sovereign rollups #99
    Dependencies:
     - [x] #95
     - [x] #94 
     - [x] #93 (issue?)
- [x] Minimal CLI with configuration file #104
- [ ] Implement CLI commands #124
- [ ] Test CLIs all the way to packet relaying for Cosmos <-> Cosmos
- [ ] Implement Cosmos -> Sovereign relaying context
    - [x] Send a simple Tx to Sovereign #100
       - [x] requires #96
    - [ ] Send CreateClient and UpdateClient from Cosmos to Sovereign 
       - [x] #101
       - [ ] #243 (@soareschen)
- [ ] Implement Sovereign -> Cosmos relaying context
    - [x] Send CreateClient for Sovereign to Cosmos #97
    - [ ] UpdateClient from Sovereign to Cosmos (@soareschen, @ljoss17)
       - [x] #98
       - [x] #244
- [ ] Implement bidirectional connection handshake 
  - #245
- [ ] Implement bidirectional channel handshake 
  - #246
- [ ] Implement bidirectional packet relaying 
  - [x] #272
  - [x] #275
- [ ] Integrate event source for Sovereign for automation/reactivity
- [ ] Integrate with the on-chain Sovereign light client

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged

```[tasklist]
### Tasks
- [ ] https://github.com/informalsystems/hermes-sdk/issues/94
- [ ] https://github.com/informalsystems/hermes-sdk/issues/95
- [ ] https://github.com/informalsystems/hermes-sdk/issues/96
- [ ] https://github.com/informalsystems/hermes-sdk/issues/97
- [ ] https://github.com/informalsystems/hermes-sdk/issues/98
- [ ] https://github.com/informalsystems/hermes-sdk/issues/100
- [ ] https://github.com/informalsystems/hermes-sdk/issues/99
- [ ] https://github.com/informalsystems/hermes-sdk/issues/101
```

**Comment by soareschen** [comment]
This is now done.
