### ISSUE TITLE
Implement IBC message builder components for Sovereign rollup

### ISSUE THREAD

**Issue by soareschen** [informalsystems/hermes-sdk#280]
It is rather straightforward to implement the IBC message builder components for Sovereign rollup, as they are pretty similar to the message builder implementations for Cosmos-to-Cosmos.

The main differences are:

- A dummy signer field is used, by calling `Signer::dummy()`.
  - cc @farhard: it is possible to make it such that IBC message types for sovereign-ibc do not include this field at all? Or should the proper signer be used eventually?
- The message is encoded into `Any`, and wrapped inside `SovereignMessage`.

Assignees can use the following implementations as reference:

- `BuildCreateCosmosClientMessageOnSovereign` for `CreateClientMessageBuilder<SovereignChain, CosmosChain>`.
- `BuildUpdateCosmosClientMessageOnSovereign` for `UpdateClientMessageBuilder<SovereignChain, CosmosChain>`

## Tasks

- [ ] `ConnectionHandshakeMessageBuilder<SovereignChain, CosmosChain>` 
    - Part of #245
    - Fill in the `todo!()` for `BuildCosmosConnectionHandshakeMessageOnSovereign`
- [ ] `ChannelHandshakeMessageBuilder<SovereignChain, CosmosChain>`
    - Part of #246
    - Fill in the `todo!()` for `BuildCosmosChannelHandshakeMessageOnSovereign`
- [x] `ReceivePacketMessageBuilder<SovereignChain, CosmosChain>`
    - Part of #274 
- [x] `AckPacketMessageBuilder<SovereignChain, CosmosChain>`
    - Part of #277 
- [x] `TimeoutUnorderedPacketMessageBuilder<SovereignChain, CosmosChain>`
    - Part of #279

**Comment by soareschen** [comment]
The listed components are already implemented, and are for your reference. By "IBC message builders" I mean message builder for IBC-related messages, such as `ReceivePacketMessageBuilder`.

You can implement new components such as:

```rust
struct BuildReceivePacketMessageOnSovereign;

impl<Chain, Counterparty> ReceivePacketMessageBuilder<Chain, Counterparty>
  for BuildReceivePacketMessageOnSovereign
where
  ...
```

**Comment by seanchen1991** [comment]
Looking at the constraints for `BuildCosmosReceivePacketMessage`, I'm not entirely sure which constraints needs to change for `BuildReceivePacketMessageOnSovereign`. More specifically, for the `Chain: HasMessageType` constraint, what should the `Message` associated type be set to?
