### ISSUE TITLE
Generalize CLI components to work with non-Cosmos chains

### ISSUE THREAD

**Issue by soareschen** [informalsystems/hermes-sdk#392]
## Summary

The current `hermes-cli` implementation is largely copied from the Hermes v1 code base. As a result, the code is tightly coupled with the Cosmos implementation. To support non-Cosmos chains on the CLI, we need to generalize the CLI code so that they can be reused to build custom CLIs that implements custom chains.

This can be done following the same CGP patterns to abstract away the CLI command runners. The context-generic CLI implementation would be placed in the `hermes-cli-components` crate.
```[tasklist]
### Tasks
- [ ] https://github.com/informalsystems/hermes-sdk/issues/522
- [ ] https://github.com/informalsystems/hermes-sdk/issues/523
- [ ] https://github.com/informalsystems/hermes-sdk/issues/526
```
