### ISSUE TITLE
Decide on how config files should be formatted

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes-sdk#46]
## Background

[#3636](https://github.com/informalsystems/hermes/issues/3636) provides some good suggestions for how config files could be formatted to better support many types of non-SDK chains. We could consider adopting some (or all) of the suggestions

## Tasks

- [ ] Decide on how config files should be formatted

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged

**Comment by romac** [comment]
We may also want to consider whether or not we want to stick with TOML or not.
